// client/src/components/TopButtons.svelte
<script>
  import IconMail from './icons/Mail.svelte'
  import IconGitHub from './icons/GitHub.svelte'
  import IconSettings from './icons/Settings.svelte'
  import { ipc } from '../ipc'
  import DrawerFormSettings from './DrawerFormSettings.svelte'

  let emailEl
  let drawerFormSettingsComp

  let buttons = [
    {
      component: IconMail,
      onClick: () => emailEl.click(),
    },
    {
      component: IconGitHub,
      onClick: () => {
        ipc.send('emitOpenURL', 'https://github.com/evillt/macmineable-release')
      },
    },
    {
      component: IconSettings,
      onClick: () => {
        drawerFormSettingsComp.show()
      },
    },
  ]
</script>

<div class="flex">
  {#each buttons as button, i (i)}
    <svelte:component
      this={button.component}
      class="w-4 ml-2 cursor-pointer"
      on:click={button.onClick}
    />
  {/each}
</div>

<a
  bind:this={emailEl}
  href="mailto:ijoec123@gmail.com?subject=[macMineable] Feedback"
  class="hidden">Feedback</a
>

<DrawerFormSettings bind:this={drawerFormSettingsComp} />

// client/src/components/TopButtons.vue
<template>
  <section class="flex">
    <component
      v-for="(button, idx) in buttons"
      :key="idx"
      :is="button.component"
      fill="currentColor"
      class="w-4 ml-2 cursor-pointer"
      @click="button.onClick"
    />
  </section>

  <a
    ref="emailFeedbackEl"
    href="mailto:ijoec123@gmail.com?subject=[macMineable] Feedback"
  ></a>
</template>

<script>
import { ref } from '@vue/reactivity'
import { RiMailFill, RiGithubFill, RiSettings4Fill } from 'vue-remix-icons'
import { useEmitter } from '../emitter'

export default {
  setup() {
    const emailFeedbackEl = ref(null)
    const emitter = useEmitter()

    const buttons = [
      {
        component: RiMailFill,
        onClick: () => {
          emailFeedbackEl.value.click()
        },
      },
      {
        component: RiGithubFill,
        onClick: () => {
          emitter.emit(
            'openURL',
            'https://github.com/evillt/macmineable-release',
          )
        },
      },
      {
        component: RiSettings4Fill,
        onClick: () => emitter.emit('openSettingDialog'),
      },
    ]

    return {
      buttons,
      emailFeedbackEl,
    }
  },
}
</script>
